---
title: "Trying out R Markdown"
author: "Jemila Gomes"
date: "16/6/2021"
output: word_document
---

1. Jemila Gomes
1. Department of forensic medicine
1. Aarhus University


# Intro


# Methods and Results

## Analysis

This is my **data** analysis *section*. 

# Discussion



```{r setup, include=FALSE}
source(here::here("R/package-loading.R"))
load(here::here("data/nhanes_small.rda")) 
knitr::opts_chunk$set(echo = FALSE)
```

```{r prettier-table, echo = FALSE, message=FALSE}
nhanes_small %>%
    filter(!is.na(diabetes)) %>% 
    group_by(diabetes, sex) %>% 
    summarise(mean_age = mean(age, na.rm = TRUE),
              mean_bmi = mean(bmi, na.rm = TRUE)) %>% 
    ungroup() %>% 
    mutate(mean_age = round(mean_age, 1),
           mean_bmi = round(mean_bmi, 1),
           sex = str_to_sentence(sex)) %>%
    
    rename("Diabetes Status" = diabetes, Sex = sex, "Mean Age" = mean_age, "Mean BMI"= mean_bmi) %>% 
    
    knitr::kable(caption = "A Prettier Table: Mean Age and BMI")
    
```
```

```

