---
title: "Data viz"
author: "Jemila Gomes"
date: "17/6/2021"
output: html_document
---

```{r setup}
#Load packages
source(here::here("R/package-loading.R"))

# load the tidied dataset
load(here::here("data/nhanes_small.rda"))
```

# One variable plots

```{r continuous-variables}
ggplot(nhanes_small, aes(x = bmi)) + 
    geom_density()


ggplot(nhanes_small, aes(x = bmi)) + 
    geom_histogram()
```

```{r discrete-variables}
ggplot(nhanes_small, aes(x = sex)) +
    geom_bar()

ggplot(nhanes_small, aes(x = diabetes)) + 
    geom_bar()
```

```{r remove-missing-diabetes}
nhanes_tidies <- nhanes_small %>% 
    filter(!is.na(diabetes))

usethis::use_data(nhanes_tidies, overwrite = T)

ggplot(nhanes_tidies, aes(x = diabetes)) + 
    geom_bar()
```
```{r}
nhanes_small %>% 
    filter(!is.na(diabetes)) %>%
    ggplot(aes(x = diabetes)) + 
    geom_bar()
    
```

# Plotting two variables

```{r 2-continuous-variables}

bmi_chol <- ggplot(nhanes_tidies, aes(x = bmi, y = tot_chol))

bmi_chol + 
    geom_point()

bmi_chol + 
    geom_hex()

bmi_chol +
    geom_smooth()

bmi_chol +
    geom_hex() + geom_smooth()
```

```{r 2-discrete-variables}
two_discrete <- nhanes_tidies %>% 
    ggplot(aes(x = diabetes, fill = sex))

two_discrete + 
    geom_bar()

two_discrete + 
    geom_bar(position = position_dodge ())
```

```{r discrete-continuous-variable}

two_mixed <- nhanes_tidies %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed + 
    geom_boxplot()

two_mixed +
    geom_jitter()

two_mixed + 
    geom_violin()
```

# Exercise to make plots with one or two variables

```{r Exercise}

# 1a. Distribution of age
ggplot(nhanes_tidies, aes(x = age)) +
    geom_histogram()
    
# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_tidies, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_tidies, aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active
ggplot(nhanes_tidies, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidies, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidies, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_tidies, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_tidies, aes(x = diabetes, y = poverty)) +
    geom_violin()
```

# Plotting three or more variables 

```{r using-colour}
 
# example for using 1 continuous and 2 discrete variables
nhanes_tidies %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes)) +
    geom_boxplot()

# example of using 3 continuous variables
nhanes_tidies %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
geom_point()

# 2 continuous and 1 discrete variable
nhanes_tidies %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) + 
    geom_point()
```

```{r using-faceting}

# side-by-side
nhanes_tidies %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) + 
    geom_point() + 
    facet_grid(cols = vars(diabetes))

# stacked
nhanes_tidies %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) + 
    geom_point() + 
    facet_grid(rows = vars(diabetes))

# 5 variables
nhanes_tidies %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point() + 
    facet_grid(rows = vars(diabetes),
               cols = vars(sex))
```

# Exercise for changing colours

```{r viridis}

# Barplot to work from, with two discrete variables
base_barplot <- nhanes_tidies %>% 
    ggplot(aes(x = diabetes, fill = sex)) +
    geom_bar(position = position_dodge())

base_barplot

base_barplot +
    scale_fill_viridis_d(option = "F")

# Scatterplot to work from, with three continuous variables
base_scatterplot <- nhanes_tidies %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

base_scatterplot +
    scale_color_viridis_c(option = "A")
```

# Changing plot appearance

```{r build-in-themes}

# Create scatterplot to play with themes
base_scatterplot2 <- base_scatterplot +
    facet_grid(rows = vars(diabetes),
               cols = vars(sex)) +
    scale_color_viridis_c()

# View the plot with the default theme
base_scatterplot2

# Try different theme
base_scatterplot2 +
    theme_minimal()

base_scatterplot2 +
    theme_bw()

base_scatterplot2 +
    theme_classic()

# Set the theme for all plots
theme_set(theme_classic())

# change title and labels
base_scatterplot2 +
    labs(title = "BMI, systolic blood pressure, and age by diabetes and sex", y = "Systolic blood pressure (mmHg)", x = "BMI (kg/m2)")

```





